# This is a basic workflow to help you get started with Actions

name: deployment workflow

# Controls when the workflow will run comment
on:
  push: 
    branches: [main]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd DukeOfHounds.github.io
            git pull
            cp index.html  ../../pub/ -f
    
